---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      network:
      - ["private_network", {ip: "33.33.33.11"}]
  - name: debian-7.4
    driver:
      network:
        - ["private_network", {ip: "33.33.33.12"}]
  - name: centos-6.5
    driver:
      network:
        - ["private_network", {ip: "33.33.33.13"}]

suites:
  - name: default
    run_list:
      - recipe[php_fpm_test::create]
    attributes:
      php:
        major_version: '5.5'
        recompile: true
      php_fpm_test:
        pool: test